# Generated by Django 6.0.2 on 2026-03-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='AccountListing',
            new_name='account_listing',
        ),
    ]
