# Generated by Django 6.0.2 on 2026-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_accountlisting_order_account_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transfer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transfer_password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transfer_proof',
            field=models.ImageField(blank=True, null=True, upload_to='transfer_proofs/'),
        ),
    ]
